### ISSUE TITLE
Database error of class SyntaxErrorOrAccessRuleViolation occured

### ISSUE THREAD

**Issue by ghost** [altLab/liquid-feedback-docker#6] opened 2018-04-23 01:45 UTC
Thank you very much for your work!
This is just great!

I just build an image and get this on startup:

```
Starting PostgreSQL 9.4 database server: main.
Starting web server: lighttpd.
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
> Event:send_notifications_loop()
> 
(error object is not a string)
```

and on accessing the webpage:
```
Database error of class SyntaxErrorOrAccessRuleViolation occured:
permission denied for relation session

Stack trace follows:
[C]: in function 'escalate'
../lib/mondelefant.lua:1180: in function 'save'
/opt/lf/frontend/model/session.lua:24: in function 'new'
/opt/lf/frontend/app/main/_filter/20_session.lua:5: in function 'func'
../env/execute/file_path.lua:24: in function 'file_path'
../env/execute/_add_filters_by_path.lua:17: in function 'wrapper_func'
../env/execute/wrapped.lua:21: in function <../env/execute/wrapped.lua:11>
(tail call): ?
(tail call): ?
../env/execute/filtered_view.lua:28: in function 'filtered_view'
webmcp.lua:382: in function <webmcp.lua:257>
[C]: in function 'xpcall'
webmcp.lua:256: in main chunk
[C]: in function 'pcall'
/opt/lf/webmcp/cgi-bin/webmcp-wrapper.lua:7: in main chunk
[C]: ?
```

It seems to be a permission problem and in your TODO file you first point is:
fix db table permissions issue

Also:
I couldnt find any log files... are there somewhere?

**Comment by pangelo** [comment] 2020-03-21 20:40
Hello, thanks for testing the image.

If this is still relevant to you, could you please test with the latest image (LF 3.2, debian buster and postgres 11) and check if you can reproduce this issue?

**Comment by pangelo** [comment] 2020-09-19 11:58
Closing issue since there have been no further reports on this.

**Closed as completed by pangelo** 2020-09-19 11:58 UTC
